name: coin_gecko_graduation_project_metorship
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  audioplayers: ^6.5.1
  cherry_toast: ^1.13.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  get_it: ^9.1.0
  go_router: ^17.0.0
  injectable: ^2.6.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.2
  firebase_core: ^4.2.1
  toastification: ^3.0.3
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^8.1.6

dev_dependencies:
  retrofit_generator: ^10.2.0
  injectable_generator:
  # add build runner if not already added
  build_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/icons/
    - assets/onboarding/
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
